services:
  firefox:
     build:
       target: firefox
     command:
     - /usr/bin/firefox
     - --display=:1
     - --kiosk
     - --marionette
     - https://orteil.dashnet.org/cookieclicker/
     ports:
     - 2828:2828
     volumes:
     - tmp:/tmp
     - firefox:/home/user/.mozilla/firefox

     depends_on:
       vncserver:
         condition: service_healthy

  vncserver:
     build:
       target: vncserver
     command:
     - /usr/bin/vncserver
     - --I-KNOW-THIS-IS-INSECURE
     - -fg
     - -geometry=1440x2560
     - -localhost=no
     - -SecurityTypes=None
     - :1
     volumes:
     - tmp:/tmp

     healthcheck:
       test: ["CMD", "test", "-S", "/tmp/.X11-unix/X1"]
       interval: 5s
       retries: 12

  novnc:
     build:
       target: novnc
     command:
     - /usr/bin/websockify
     - --web=/usr/share/novnc
     - '6080'
     - vncserver:5901
     ports:
     - 6080:6080

volumes:
  tmp:
    driver: tmpfs
  firefox:
