---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookieclicker
spec:
  selector:
    matchLabels:
      app: cookieclicker
  template:
    metadata:
      labels:
        app: cookieclicker
    spec:
      initContainers:
        - name: vncserver
          image: ghcr.io/hakuyume/cookieclicker:vncserver
          command:
            - vncserver
            - -fg
            - -geometry=1440x2560
            - -SecurityTypes=None
            - :1
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          restartPolicy: Always
          startupProbe:
            exec:
              command: [test, -S, /tmp/.X11-unix/X1]

      containers:
        - name: firefox
          image: ghcr.io/hakuyume/cookieclicker:firefox
          command:
            - firefox
            - --display=:1
            - --kiosk
            - --marionette
            - https://orteil.dashnet.org/cookieclicker/
          volumeMounts:
            - name: tmp
              mountPath: /tmp
        - name: geckodriver
          image: ghcr.io/hakuyume/cookieclicker:geckodriver
          command:
            - geckodriver
            - --connect-existing
            - --host=0.0.0.0
            - --marionette-port=2828
            - --port=30516
        - name: ffmpeg
          image: ghcr.io/hakuyume/cookieclicker:ffmpeg
          command:
            - ffmpeg
            - -f
            - x11grab
            - -i
            - :1
            - -f
            - hls
            - -hls_segment_filename
            - video%03d.ts
            - -hls_flags
            - delete_segments
            - video.m3u8
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: hls
              mountPath: /hls
          workingDir: /hls
        - name: nginx
          image: nginx
          volumeMounts:
            - name: hls
              mountPath: /usr/share/nginx/html/hls
              readOnly: true

      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
        - name: hls
          emptyDir:

---
apiVersion: v1
kind: Service
metadata:
  name: cookieclicker
spec:
  type: NodePort
  selector:
    app: cookieclicker
  ports:
    - name: webdriver
      protocol: TCP
      port: 30516
      nodePort: 30516
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30656
